name: Publish to Snap Store

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # 1. Snapcraft tool install karna
    - name: Install Snapcraft
      run: |
        sudo snap install snapcraft --classic

    # 2. Game ko direct bina password ke build karna (Destructive Mode)
    - name: Build Snap
      run: |
        sudo snapcraft build --destructive-mode

    # 3. Release upload karna aapke token ke sath
    - name: Upload to Snap Store
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
      run: |
        snapcraft upload --release=stable crewmate-rush-space-escape-runner_*.snap
