name: Publish to Snap Store

on:
  push:
    branches: [ main ]
  workflow_dispatch: # <--- Yeh line add karni hai taake manual run button aa jaye

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Snapcraft Environment
      run: |
        sudo snap install snapcraft --classic
        
    - name: Build Snap Package
      run: |
        sg lxd -c "snapcraft --verbose"

    - name: Upload to Store
      run: |
        echo "Build successful! Ready for store release."
