name: Publish to Snap Store

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Ubuntu ka official tool jo aapka snap unke servers par build aur publish karega
    - name: Remote Build and Publish Snap
      uses: didrocks/snapcraft-build-action@v1
      with:
        snapcraft_token: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
