name: Generate Snap Token
on: workflow_dispatch
jobs:
  token:
    runs-on: ubuntu-latest
    steps:
    - name: Get Login Link
      run: |
        echo "=========================================================="
        echo "Niche diye gaye official link par click karke login karein:"
        echo "https://ubuntu.com"
        echo "=========================================================="
